# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ilya/Downloads/opencv-3.1.0/workspace/FaceDetect

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ilya/Downloads/opencv-3.1.0/workspace/FaceDetect

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ilya/Downloads/opencv-3.1.0/workspace/FaceDetect/CMakeFiles /home/ilya/Downloads/opencv-3.1.0/workspace/FaceDetect/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ilya/Downloads/opencv-3.1.0/workspace/FaceDetect/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named facedetect

# Build rule for target.
facedetect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 facedetect
.PHONY : facedetect

# fast build rule for target.
facedetect/fast:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/build
.PHONY : facedetect/fast

arg.o: arg.cpp.o
.PHONY : arg.o

# target to build an object file
arg.cpp.o:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/arg.cpp.o
.PHONY : arg.cpp.o

arg.i: arg.cpp.i
.PHONY : arg.i

# target to preprocess a source file
arg.cpp.i:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/arg.cpp.i
.PHONY : arg.cpp.i

arg.s: arg.cpp.s
.PHONY : arg.s

# target to generate assembly for a file
arg.cpp.s:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/arg.cpp.s
.PHONY : arg.cpp.s

autocamera.o: autocamera.cpp.o
.PHONY : autocamera.o

# target to build an object file
autocamera.cpp.o:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/autocamera.cpp.o
.PHONY : autocamera.cpp.o

autocamera.i: autocamera.cpp.i
.PHONY : autocamera.i

# target to preprocess a source file
autocamera.cpp.i:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/autocamera.cpp.i
.PHONY : autocamera.cpp.i

autocamera.s: autocamera.cpp.s
.PHONY : autocamera.s

# target to generate assembly for a file
autocamera.cpp.s:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/autocamera.cpp.s
.PHONY : autocamera.cpp.s

automotion.o: automotion.cpp.o
.PHONY : automotion.o

# target to build an object file
automotion.cpp.o:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/automotion.cpp.o
.PHONY : automotion.cpp.o

automotion.i: automotion.cpp.i
.PHONY : automotion.i

# target to preprocess a source file
automotion.cpp.i:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/automotion.cpp.i
.PHONY : automotion.cpp.i

automotion.s: automotion.cpp.s
.PHONY : automotion.s

# target to generate assembly for a file
automotion.cpp.s:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/automotion.cpp.s
.PHONY : automotion.cpp.s

autozoom.o: autozoom.cpp.o
.PHONY : autozoom.o

# target to build an object file
autozoom.cpp.o:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/autozoom.cpp.o
.PHONY : autozoom.cpp.o

autozoom.i: autozoom.cpp.i
.PHONY : autozoom.i

# target to preprocess a source file
autozoom.cpp.i:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/autozoom.cpp.i
.PHONY : autozoom.cpp.i

autozoom.s: autozoom.cpp.s
.PHONY : autozoom.s

# target to generate assembly for a file
autozoom.cpp.s:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/autozoom.cpp.s
.PHONY : autozoom.cpp.s

facedetect.o: facedetect.cpp.o
.PHONY : facedetect.o

# target to build an object file
facedetect.cpp.o:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/facedetect.cpp.o
.PHONY : facedetect.cpp.o

facedetect.i: facedetect.cpp.i
.PHONY : facedetect.i

# target to preprocess a source file
facedetect.cpp.i:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/facedetect.cpp.i
.PHONY : facedetect.cpp.i

facedetect.s: facedetect.cpp.s
.PHONY : facedetect.s

# target to generate assembly for a file
facedetect.cpp.s:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/facedetect.cpp.s
.PHONY : facedetect.cpp.s

statemachine.o: statemachine.cpp.o
.PHONY : statemachine.o

# target to build an object file
statemachine.cpp.o:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/statemachine.cpp.o
.PHONY : statemachine.cpp.o

statemachine.i: statemachine.cpp.i
.PHONY : statemachine.i

# target to preprocess a source file
statemachine.cpp.i:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/statemachine.cpp.i
.PHONY : statemachine.cpp.i

statemachine.s: statemachine.cpp.s
.PHONY : statemachine.s

# target to generate assembly for a file
statemachine.cpp.s:
	$(MAKE) -f CMakeFiles/facedetect.dir/build.make CMakeFiles/facedetect.dir/statemachine.cpp.s
.PHONY : statemachine.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... facedetect"
	@echo "... arg.o"
	@echo "... arg.i"
	@echo "... arg.s"
	@echo "... autocamera.o"
	@echo "... autocamera.i"
	@echo "... autocamera.s"
	@echo "... automotion.o"
	@echo "... automotion.i"
	@echo "... automotion.s"
	@echo "... autozoom.o"
	@echo "... autozoom.i"
	@echo "... autozoom.s"
	@echo "... facedetect.o"
	@echo "... facedetect.i"
	@echo "... facedetect.s"
	@echo "... statemachine.o"
	@echo "... statemachine.i"
	@echo "... statemachine.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

