.TH "arg.h" 3 "Пн 23 Май 2016" "Version v2.0.1" "faceDetect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arg.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBArg< T >\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для faceDetect из исходного текста\&.
