.TH "autozoom.h" 3 "Пн 23 Май 2016" "Version v2.0.1" "faceDetect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autozoom.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'statemachine\&.h'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBAutoZoom\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для faceDetect из исходного текста\&.
